Feature/components spin
IduxFE/components pull request #101
Opened 2021-01-03 02:47 UTC by liuzaijiang

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IduxFE/components/blob/main/docs/contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-01-03 03:10 UTC, danranVm commented
PR 的 title 不符合规范，
commit 需要做一下合并，使用 rebase 而不是 merge 操作
另外 lint 的 CI 挂掉了，还需要在本地执行一下 `npm run lint-fix` 看看是哪里不对

2021-01-03 06:39 UTC, danranVm requested changes

2021-01-03 06:39 UTC, danranVm commented on packages/components/spin/docs/index.zh.md
> +CONFIGS
```suggestion
#### props
```

2021-01-03 06:39 UTC, danranVm commented on packages/components/spin/docs/index.zh.md
> +SLOTS
```suggestion
#### slots
```

2021-01-03 06:39 UTC, danranVm commented on packages/components/spin/docs/index.zh.md
> +|参数 | 说明 |  类型  | 默认值 | 是否支持全局配置|
```suggestion
| 参数 | 说明 |  类型  | 全局配置 | 默认值 | 备注 |
```

2021-01-03 06:39 UTC, danranVm commented on packages/components/spin/docs/index.zh.md
> +| `tipAlign`| 文字描述与加载图标的排列方式 | `string` | `vertical(vertical：文字排列在图标下方；horizontal： 文字排列在图标同水平方向的后方)`| `true`|
```suggestion
| `tipAlign`| 文字描述与加载图标的排列方式 | `vertical \| horizontal ` | `vertical`| - | vertical：文字排列在图标下方；horizontal： 文字排列在图标同水平方向的后方 |
```

2021-01-03 06:39 UTC, danranVm commented on packages/components/spin/src/Spin.vue
> +      ]
```suggestion
      if(!props.spinning  || !tip.value){
        return []
      } 
      const size = props.size ?? spinConfig.size
      const tipAlign =  props.tipAlign ?? spinConfig.tipAlign
      return [
        `ix-spin-spinner-tip-${tipAlign}` ,
        size !== 'medium' ? `ix-spin-spinner-${size}` : '',
      ]
```

2021-01-04 07:54 UTC, Usualminds reviewed
@liuzaijiang 没什么问题，层级那个你确认下是否需要修改

2021-01-04 07:54 UTC, Usualminds commented on packages/components/spin/style/index.less
> +    z-index: 12;
` z-index: 12` 建议改为 10 整数

2021-01-04 08:33 UTC, danranVm approved these changes

2021-01-04 08:37 UTC, Usualminds approved these changes

2021-01-04 08:38 UTC, danranVm approved these changes

2021-01-04 09:17 UTC, danranVm commented
@liuzaijiang 感谢你的 PR， LGTM.

2021-01-04 09:24 UTC, merged