feat(comp:card): add card comp
IduxFE/components pull request #129
Opened 2021-01-10 15:49 UTC by CruellyJoHn

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IduxFE/components/blob/main/docs/contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-01-10 15:51 UTC, CruellyJoHn commented
@danranVm 麻烦大佬review一下

2021-01-11 03:18 UTC, danranVm requested changes

2021-01-11 03:18 UTC, danranVm commented on packages/components/card/src/Card.vue
> +  <div class="ix-card" :class="classes">
Dom 结构调整一下
```html
<div class="ix-card">
  <div class="ix-card-head">
  </div>
  <div class="ix-card-body">
  </div>
  <div class="ix-card-footer">
  </div>
</div>
```

2021-01-11 03:18 UTC, danranVm commented on packages/components/card/src/Card.vue
> +    const size = props.size !== undefined ? props.size : cardConfig.size
```suggestion
    const hoverable = props.hoverable ?? cardConfig.hoverable
    const borderless = props.borderless ?? cardConfig.borderless
    const size = props.size ?? cardConfig.size
```

2021-01-11 03:18 UTC, danranVm commented on packages/components/card/src/Card.vue
> +    const isShowLoading = computed(() => (props.loading !== undefined ? props.loading : cardConfig.loading))
```suggestion
    const isShowLoading = computed(() => (props.loading ?? cardConfig.loading))
```

2021-01-11 03:18 UTC, danranVm commented on packages/components/card/src/Card.vue
> +    const isShowFooter = computed(() => !!slots.extra)
判断插槽是否存在需要考虑下面这种情况，参考下 button 组件的 `hasDefaultSlot`
```html
<template v-if="isShow" #footer>
  <span>this is footer</span>
</template>
```

2021-01-11 03:18 UTC, danranVm commented on packages/components/card/src/types.ts
> +import type { ComponentSize } from '@idux/components/core/types'
这个文件结构有改动，参考最新的 button 组件代码

2021-01-11 03:18 UTC, danranVm commented on packages/components/card/style/index.less
> +@import '../../style/default.less';
。。。 最基本的样式都木有么？ :cry:

2021-01-12 02:20 UTC, clfeng commented on packages/components/card/src/Card.vue
> +            <a>{{ title }}</a>
这里使用普通的span的标签就好了，不要使用功能a标签，a标签的用处更多的是链接，但是在当前的场景下，连a标签的href都没法配置，使用a标签意义不大

2021-01-12 02:20 UTC, clfeng commented on packages/components/card/src/Card.vue
> +            <a>{{ extra }}</a>
同上，建议使用span标签

2021-01-12 02:27 UTC, clfeng commented on packages/components/card/src/Card.vue
> +      size !== 'medium' ? `ix-card-${size}` : '',
medium本身也是合法的配置项，然后按照你这里的逻辑，个人觉得应该保持一致性，给组件设置ix-card-medium类；然后这个类所设置的大小跟默认的一致便是了；更好的是默认的不设置大小，然后组件内部更具外部传值得到对应控制尺寸的类；这个类控制着组件大小，然后内部做好传值不合法的处理

2021-01-20 16:00 UTC, CruellyJoHn commented
@clfeng @danranVm 麻烦review一下

2021-01-21 01:45 UTC, danranVm commented
@CruellyJoHn 需要进行 `rebase -i` 操作，合并掉 commit.

2021-01-24 06:30 UTC, closed without merging