feat(comp: result): add result component
IduxFE/components pull request #136
Opened 2021-01-13 06:53 UTC by LaamGinghong

fix #112

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IduxFE/components/blob/main/docs/contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-01-13 06:55 UTC, LaamGinghong commented
之前API设计时 `status` 包含的 `403` `404` `500` 先暂时去掉，设计给出的设计稿和 ant 的差别有点大。

2021-01-13 13:50 UTC, danranVm requested changes

2021-01-13 13:50 UTC, danranVm commented on packages/components/result/src/Result.vue
> +    </slot>
```suggestion
    <div v-if="title || hasTitleSlot" class="ix-result-title">
      <slot name="title">{{ title }}</slot >
    </div>
    <div v-if="subtitle || hasSubtitleSlot" class="ix-result-subtitle">
      <slot name="subtitle">{{ subtitle}}</slot >
    </div>
```
这样会不会更好些？否则用户通过 slot 传进来的样式都不统一

2021-01-13 13:50 UTC, danranVm commented on packages/components/result/style/mixins.less
> +  info: @blue;
```suggestion
  success:  @result-success-color;
  warning: @result-warning-color;
  error: @result-error-color;
  info: @result-info-color;
```

2021-01-13 13:50 UTC, danranVm commented on packages/components/result/style/index.less
> +@icon-prefix: ~'@{idux-prefix}-icon';
```suggestion
```

这里不需要定义 `@icon-prefix` 可以直接引用。

2021-01-13 13:50 UTC, danranVm commented on packages/components/result/style/index.less
> +    line-height: 1.8;
定义下变量？

2021-01-13 13:50 UTC, danranVm commented on packages/components/result/style/index.less
> +    line-height: 1.6;
定义下变量？

2021-01-13 13:50 UTC, danranVm commented on packages/components/result/style/index.less
> +        margin-right: 0;
定义下变量？

2021-01-13 13:50 UTC, danranVm commented on packages/components/style/default.less
> +@result-padding: @spacing-gutter * 6 @spacing-gutter * 4;
这些变量记得在 index.zh.md 中贴一下。

2021-01-13 13:54 UTC, LaamGinghong commented on packages/components/result/src/Result.vue
> +    </slot>
我觉得这种可以规定一下，slot传进来的到底是完全交给调用方来管理，还是保留我们自己的一些样式配置

2021-01-13 13:55 UTC, LaamGinghong commented on packages/components/result/style/mixins.less
> +  info: @blue;
这个颜色我暂时是随便定的，后续等我把那个色谱做出来了再管理

2021-01-13 13:56 UTC, LaamGinghong commented on packages/components/result/style/index.less
> +        margin-right: 0;
这个应该不需要，这个是为了清楚最后一个的右边距

2021-01-13 13:57 UTC, LaamGinghong commented on packages/components/style/default.less
> +@result-padding: @spacing-gutter * 6 @spacing-gutter * 4;
那之前组件的文档都要加上啊

2021-01-14 01:34 UTC, danranVm commented on packages/components/result/src/Result.vue
> +    </slot>
保留我们的样式设置，你看其他组件包括，你这个组件的  extra 和 content

2021-01-14 01:34 UTC, danranVm commented on packages/components/result/style/mixins.less
> +  info: @blue;
先定义成变量，到时候改也是修改 result-xxx-color 的值，不会再来改这个组件的代码

2021-01-14 01:35 UTC, danranVm commented on packages/components/result/style/index.less
> +        margin-right: 0;
OK

2021-01-14 01:36 UTC, danranVm commented on packages/components/style/default.less
> +@result-padding: @spacing-gutter * 6 @spacing-gutter * 4;
新组件都要加上，旧组件有空补。

2021-01-14 09:30 UTC, LaamGinghong commented
所以less的变量是全局的？我完全没有引用icon的样式居然也可以用里面的变量

2021-01-14 09:30 UTC, LaamGinghong commented
@danranVm 请重新review

2021-01-14 11:14 UTC, danranVm commented
> 所以less的变量是全局的？我完全没有引用icon的样式居然也可以用里面的变量

对的，它没有 module 一说。

2021-01-14 11:27 UTC, LaamGinghong commented
> > 所以less的变量是全局的？我完全没有引用icon的样式居然也可以用里面的变量
> 
> 对的，它没有 module 一说。

我靠，但是ide在没有引用的情况下报了警告

2021-01-14 11:46 UTC, danranVm commented on packages/components/style/default.less
> +@result-info-color: @blue;
```suggestion
@result-success-color:  @success-color;
@result-warning-color:  @warning-color;
@result-error-color: @error-color;
@result-info-color: @info-color;
```

2021-01-14 12:06 UTC, danranVm approved these changes

2021-01-14 12:32 UTC, LaamGinghong commented
@danranVm 已合并成一个commit

2021-01-15 01:38 UTC, danranVm commented
@huangtenghui review 一下

2021-01-16 02:34 UTC, danranVm commented
感谢PR, LGTM.

2021-01-16 02:35 UTC, merged