feat(comp: typography): add directive typography
IduxFE/components pull request #148
Opened 2021-01-18 09:13 UTC by LaamGinghong

fix #130

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IduxFE/components/blob/main/docs/contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-01-19 11:13 UTC, danranVm requested changes

2021-01-19 11:13 UTC, danranVm commented on packages/components/style/default.less
> +@typography-kbd-border-width: @border-size-sm @border-size-sm @border-size-md;
```suggestion
@typography-kbd-border: @border-size-sm solid @grey-d30;
```

2021-01-19 11:13 UTC, danranVm commented on packages/components/style/default.less
> +@typography-title-margin-top: 1.2em;
```less
@typography-title-margin-bottom: 0.5em;
@typography-title-color: @black-l10;
@typography-title-font-weight: @font-weight-lg;
```
这三个弄成公用的吧，title 的等级应该只改变大小才对。
同时 `font-size` 和 `line-height` 能使用同一个 base 变量，然后其他变量通过这个 base 变量去计算。

2021-01-19 11:13 UTC, danranVm commented on packages/components/typography/demo/text.md
> +  <span v-typography><a href="https://ng.ant.design/" target="_blank">Text (link)</a></span>
```suggestion
  <span v-typography><a href="https://github.com/IduxFE/components" target="_blank">Text (link)</a></span>
```

2021-01-19 12:30 UTC, LaamGinghong commented on packages/components/index.ts
> +const directives: Record<string, Directive> = {
不好吧，还是保持在最顶层，es的规范也是这么说的

2021-01-19 12:30 UTC, LaamGinghong commented on packages/components/style/default.less
> +@typography-kbd-border-width: @border-size-sm @border-size-sm @border-size-md;
这个拆不了，因为宽度上左右是一样的，但是下面会粗一点

2021-01-19 12:31 UTC, LaamGinghong commented on packages/components/style/default.less
> +@typography-title-margin-top: 1.2em;
就是不知道她是怎么算的，我去看下ant的源码

2021-01-19 12:32 UTC, LaamGinghong commented on packages/components/typography/demo/text.md
> +  <span v-typography><a href="https://ng.ant.design/" target="_blank">Text (link)</a></span>
尴尬😅

2021-01-20 03:24 UTC, danranVm commented on packages/components/index.ts
> +const directives: Record<string, Directive> = {
我是感觉把 components 和 directives 做一下区分？
或者我们再拆成两个文件，components.ts, directives.ts

2021-01-20 03:25 UTC, danranVm commented on packages/components/style/default.less
> +@typography-kbd-border-width: @border-size-sm @border-size-sm @border-size-md;
emmm 算你狠。

2021-01-20 03:42 UTC, LaamGinghong commented on packages/components/index.ts
> +const directives: Record<string, Directive> = {
这样更合适一些，然后 index 直接暴露所有

2021-01-20 09:27 UTC, LaamGinghong commented on packages/components/index.ts
> +const directives: Record<string, Directive> = {
这个放到下一个pr来做吧，除了改这些，到时还得改模版，有点忙不过来了

2021-01-20 10:08 UTC, LaamGinghong commented
@danranVm @hele10086 请重新review

2021-01-20 10:42 UTC, danranVm approved these changes
LGTM.

2021-01-20 10:45 UTC, merged