feat(comp:rate): add cpmponent rate
IduxFE/components pull request #152
Opened 2021-01-19 09:26 UTC by CocaColf

fix #34

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IduxFE/components/blob/main/docs/contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-01-19 12:07 UTC, coolyuantao requested changes
全局配置功能漏了，另外 @danranVm 看下关于几个背景颜色的配置是否只需要less变量？

2021-01-19 12:54 UTC, CocaColf commented on packages/components/rate/src/Rate.vue
> +  emits: ['update:modelValue', 'change'],
这个应该是需要的，我试了如果只有change事件的话，功能没有按预期运行。
关于这个我是从这里看的：https://v3.vuejs.org/guide/migration/v-model.html#overview

2021-01-19 13:06 UTC, danranVm commented on packages/components/rate/docs/index.zh.md
> +| `modelValue` | 高亮的数目（分数） | `string \| number` | 0 | - | - |
是因为要支持 v-model 才换的 modelValue 吧

2021-01-20 02:55 UTC, danranVm requested changes

2021-01-20 02:55 UTC, danranVm commented on packages/components/icon/src/icons.ts
> +import { Smile } from '../definitions/smile'
记得换成 `Star`

2021-01-20 02:55 UTC, danranVm commented on packages/components/rate/docs/index.zh.md
> +| `allowClear` | 二次点击元素后清除选择 | `boolean` | false | - |-|
建议 `count`, `icon`, `allowHalf`, `allowClear` 支持全局配置。

2021-01-20 02:55 UTC, danranVm commented on packages/components/rate/src/Rate.vue
> +    handleMouseEnter(item: number, e: MouseEvent) {
methods 中的函数都换成 composition api 风格吧，在 setup 中定义。

2021-01-20 08:09 UTC, CocaColf commented on packages/components/rate/src/Rate.vue
> +    handleMouseEnter(item: number, e: MouseEvent) {
> methods 中的函数都换成 composition api 风格吧，在 setup 中定义。

已修改

2021-01-20 08:13 UTC, CocaColf commented on packages/components/rate/docs/index.zh.md
> +| `backgroundColor` | 未被选择时的颜色 | `string` | `#c6d1de` | - | - |
> 这两个 props 不提供吧，通过 less 变量去控制？

已提供全局less变量

2021-01-20 08:13 UTC, CocaColf commented on packages/components/rate/docs/index.zh.md
> +| `allowClear` | 二次点击元素后清除选择 | `boolean` | false | - |-|
> 建议 `count`, `icon`, `allowHalf`, `allowClear` 支持全局配置。

这几个都支持全局配置

2021-01-20 08:20 UTC, CocaColf commented on packages/components/icon/src/icons.ts
> +import { Smile } from '../definitions/smile'
> 记得换成 `Star`

已替换，默认为Star

2021-01-20 09:30 UTC, danranVm commented on packages/components/rate/src/Rate.vue
> +    )
```suggestion
    watchEffect(
      () => {
        const value = toNumber(props.value)
        score.value = value 
        touchHalf.value = value  !== Math.floor(value)
      },
    )
```

2021-01-20 09:30 UTC, danranVm commented on packages/components/rate/src/Rate.vue
> +    }
还是感觉这里代码全部都是通过 index 去做一些判断和操作，不够优雅。
后面有机会还是重构成 antd 的那种模式？ 单独抽成一个 rate-item 组件。

2021-01-20 09:30 UTC, danranVm commented on packages/components/rate/src/types.ts
> +export type RateRef = InstanceType<DefineComponent<RateProps, Methods>>
如果是为测试服务的类型，就定义到 测试文件中就好了。

2021-01-20 09:30 UTC, danranVm commented on packages/components/rate/__tests__/rate.spec.ts
> +    expect(vm.value).toEqual(0.5)
不能通过这种方式去触发 handleMouseEnter，handleMouseLeave，jest 应该有模拟 hover 的API。
下面几个测试用例都是的。。。

2021-01-20 09:30 UTC, danranVm commented on packages/components/rate/__tests__/rate.spec.ts
> +    expect(vm.value).toEqual(3)
这个测试没有意义，应该不是这么测的。
你可以默认 2 的时候，看看是否有两个 icon 高亮，
设置 3 的时候，看看是否有三个 icon 高亮。

另外还可以看看设置 2.3，2.5 这种情况。

2021-01-20 09:30 UTC, danranVm commented on packages/components/rate/__tests__/rate.spec.ts
> +    const myRateRef = vm.$refs.myRateRef as RateRef
```suggestion
    const rateRef =  wrapper.vm.$refs.myRateRef as RateRef
```

不要用 my...这种命名。

2021-01-21 07:26 UTC, CocaColf commented on packages/components/rate/__tests__/rate.spec.ts
> +    addIconDefinitions([Star])
> 这个移除掉？，要测修改 icon 的话，用已经静态加载的吧。 比如 `up, down` 之类的

已修改

2021-01-21 07:26 UTC, CocaColf commented on packages/components/rate/src/types.ts
> +export type RateRef = InstanceType<DefineComponent<RateProps, Methods>>
> 如果是为测试服务的类型，就定义到 测试文件中就好了。

好。此类型现已不需要，删除处理 😄

2021-01-21 07:27 UTC, CocaColf commented on packages/components/rate/src/Rate.vue
> +    }
> 还是感觉这里代码全部都是通过 index 去做一些判断和操作，不够优雅。
> 后面有机会还是重构成 antd 的那种模式？ 单独抽成一个 rate-item 组件。

后面研究一下，先这样实现 😸

2021-01-21 07:28 UTC, CocaColf commented on packages/components/rate/__tests__/rate.spec.ts
> +    expect(vm.value).toEqual(0.5)
> 不能通过这种方式去触发 handleMouseEnter，handleMouseLeave，jest 应该有模拟 hover 的API。
> 下面几个测试用例都是的。。。

已修改，通过 `wrapper.trigger('mousemove')` 这种方式测试

2021-01-21 07:44 UTC, CocaColf commented
@danranVm 我已修改上次 review 提出的问题，麻烦再次review

2021-01-21 09:03 UTC, danranVm requested changes

2021-01-21 09:03 UTC, danranVm commented on packages/components/rate/src/Rate.vue
> +      emit('change', emitValue)
这里应该是要对比一下值有没有发生改变再 emit? 
另外这个change 是不是没有意义。

2021-01-21 09:03 UTC, danranVm commented on packages/components/rate/src/Rate.vue
> +    count: PropTypes.oneOfType([Number, String]),
```suggestion
    count: withUndefined<PropTypes.oneOfType([Number, String])>,
```

oneOfType 的时候，需要加一个 withUndefined

2021-01-21 09:10 UTC, CocaColf commented on packages/components/rate/src/Rate.vue
> +      emit('change', emitValue)
> 这里应该是要对比一下值有没有发生改变再 emit?
> 另外这个change 是不是没有意义。


1. 想了想，应该是要比对一下
2. change 的话因为我们的 api 里定义了会抛出一个 `change` 事件

2021-01-21 09:16 UTC, danranVm commented on packages/components/rate/src/Rate.vue
> +        emitValue = 0
不要用这种写法。
```suggestion
      let clearValue = false
      let emitValue = 0
```

2021-01-21 11:24 UTC, CocaColf commented on packages/components/rate/src/Rate.vue
> +      emit('change', emitValue)
> > 这里应该是要对比一下值有没有发生改变再 emit?
> > 另外这个change 是不是没有意义。
> 
> 1. 想了想，应该是要比对一下
> 2. change 的话因为我们的 api 里定义了会抛出一个 `change` 事件

最终去掉了 change 事件

2021-01-21 11:32 UTC, CocaColf commented
@danranVm I had fix all the problems and I do believe in it's my last time to commit!!! 🤣

2021-01-21 11:52 UTC, danranVm commented
@CocaColf 感谢 PR, LGTM.

2021-01-21 11:53 UTC, merged