feat(comp: checkbox): add checkbox component
IduxFE/components pull request #162
Opened 2021-01-21 18:06 UTC by liuzaijiang

fix #120

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IduxFE/components/blob/main/docs/contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

@danranVm @LaamGinghong

2021-01-22 01:58 UTC, LaamGinghong requested changes

2021-01-22 01:58 UTC, LaamGinghong commented on jest.config.js
> +    // u can change this option to a more specific folder for test single component or util when dev
怎么还有配置的修改
@danranVm 你看看咋回事

2021-01-22 01:58 UTC, LaamGinghong commented on package.json
> +    "name": "idux",
这又是怎么回事

2021-01-22 01:58 UTC, LaamGinghong commented on packages/components/checkbox/src/CheckboxGroup.vue
> +import mitt, { Handler } from 'mitt'
这个是不是说不要用mitt，用内部实现的Subject
@danranVm

2021-01-22 01:58 UTC, LaamGinghong commented on packages/components/checkbox/src/checkbox.ts
> +import { Emitter } from 'mitt'
同上

2021-01-22 01:59 UTC, LaamGinghong commented on packages/components/checkbox/src/uses.ts
> +}
这种写法比较独特，学习到了

2021-01-22 02:01 UTC, LaamGinghong requested changes

2021-01-22 02:01 UTC, LaamGinghong commented on jest.config.js
> +}
怎么有配置文件修改的？

2021-01-22 02:01 UTC, LaamGinghong commented on package.json
> +}
这个检查一下怎么回事

2021-01-22 15:56 UTC, danranVm requested changes

2021-01-22 15:56 UTC, danranVm commented on packages/components/checkbox/__tests__/checkbox.spec.ts
> +    })
```suggestion
   
    const wrapper = mount({
      components:{IxCheckbox},
      template:`<ix-checkbox v-model:checked="checked">`
      setup(){
        const checked = ref(false)
        const changeChecked = ()=>{
          checked.value = !checked.value
        }
        return { checked, changeChecked }
      }
    })
```

2021-01-22 15:56 UTC, danranVm commented on packages/components/checkbox/__tests__/checkbox.spec.ts
> +    })
其他的测试用例都需要修改，测试都写的不对，完全不符合使用场景。

2021-01-22 15:56 UTC, danranVm commented on packages/components/checkbox/__tests__/checkbox.spec.ts
> +        onChange: mockFn,
事件应该通过 attrs 传递进去。

2021-01-22 15:56 UTC, danranVm commented on packages/components/checkbox/__tests__/checkboxGroup.spec.ts
> +  test('value(v-model) work', async () => {
这里的测试也都需要修改。

2021-01-22 15:56 UTC, danranVm commented on packages/components/checkbox/demo/Disabled.vue
> +<template>
所有文档参考 antd, demo 代码中尽量不要出现中文。

https://ng.ant.design/components/checkbox/zh

2021-01-22 15:56 UTC, danranVm commented on packages/components/checkbox/docs/index.zh.md
> +| `change` | 点击勾选框时触发 | `Function(checkValue:boolean \| string \| number)` | - |
两个组件的 change 事件我认为没有必要提供。

2021-01-22 15:56 UTC, danranVm commented on packages/components/checkbox/docs/index.zh.md
> +#### 主题变量
主题变量移到最后面去，另外它是 3级标题
```suggestion
### 主题变量
```

2021-01-24 10:52 UTC, danranVm requested changes
革命尚未成功，加油。

2021-01-24 10:52 UTC, danranVm commented on packages/components/checkbox/demo/Basic.vue
> +    checked: {{ checked }}<br />
不要这种东西，多参考一下其他组件库的文档。

2021-01-24 10:52 UTC, danranVm commented on packages/components/checkbox/docs/index.zh.md
> +支持原生input属性, 例如`value, name, id`等
> 除以下表格之外还支持原生 `<input type="checkbox" />` 元素的[所有属性](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/input/checkbox)。

2021-01-24 10:52 UTC, danranVm commented on packages/components/checkbox/docs/index.zh.md
> +|`checked` | 指定当前勾选框是否选中 |  `boolean`  | `false` | - | 支持双向绑定，使用时按照v-model:checked = 形式 |
```suggestion
|`v-model:checked` | 指定当前勾选框是否选中 |  `boolean`  | `false` | - | - |
```

2021-01-24 10:52 UTC, danranVm commented on packages/components/checkbox/docs/index.zh.md
> +| `value` | 指定选中的选项 |  `string[]`  | `[]` | - | 支持双向绑定，使用时按照v-model:value = 形式 |
同上

2021-01-24 10:52 UTC, danranVm commented on packages/components/checkbox/src/Checkbox.vue
> +      <span class="ix-checkbox-inner" :tabindex="$attrs.tabindex"></span>
这个 `span` 是用来干什么的？

2021-01-24 10:52 UTC, danranVm commented on packages/components/checkbox/src/Checkbox.vue
> +  <label class="ix-checkbox" role="checkbox" :aria-checked="isChecked" :aria-disabled="isDisabled" :class="classes">
```suggestion
  <label class="ix-checkbox" role="checkbox" :ariaChecked="isChecked" :ariaDisabled="isDisabled" :class="classes">
```

2021-01-24 10:52 UTC, danranVm commented on packages/components/checkbox/src/Checkbox.vue
> +        :true-value="trueValue"
```suggestion
        :trueValue="trueValue"
```

2021-01-24 10:52 UTC, danranVm commented on packages/components/checkbox/src/Checkbox.vue
> +        :false-value="falseValue"
```suggestion
        :falseValue="falseValue"
```

2021-01-24 10:52 UTC, danranVm commented on packages/components/checkbox/src/Checkbox.vue
> +        class="ix-checkbox-original-input"
```suggestion
        class="ix-checkbox-input"
```
上面那个 class 应该换个名字

2021-01-24 10:52 UTC, danranVm commented on packages/components/checkbox/src/Checkbox.vue
> +        v-bind="$attrs"
attrs 穿透有问题，应该把 class 和 style 过滤掉，另外 tabindex 也应该过滤掉？

2021-01-24 10:52 UTC, danranVm commented on packages/components/checkbox/src/CheckboxGroup.vue
> +import mitt, { Handler } from 'mitt'
对 换成 subject 实现。

2021-01-24 10:52 UTC, danranVm commented on packages/components/checkbox/src/CheckboxGroup.vue
> +    value: PropTypes.arrayOf(PropTypes.string),
这里为什么不 def([]) 呢？ 感觉下面很多逻辑都可以省略掉。

2021-01-24 10:52 UTC, danranVm commented on packages/components/checkbox/src/uses.ts
> +  const { attrs } = getCurrentInstance()!
这个不应该是 props 吗？我怎么感觉这段代码有 bug.

2021-01-24 10:52 UTC, danranVm commented on packages/components/checkbox/src/uses.ts
> +}
我认为要么把整个 setup 全部抽出来，要么就写在 vue 文件里面。
这样抽一半，我不认为是一个好的方式。。。

2021-01-24 10:52 UTC, danranVm commented on packages/components/checkbox/src/uses.ts
> +export { useCheckValue, useChecked, useDisabled, useClasses, useName }
每次函数单独 export 就好，不需要在这里做统一 export

2021-01-24 10:52 UTC, danranVm commented on packages/components/checkbox/src/uses.ts
> +const useCheckValue: UseCheckValue = isDisabled => {
```suggestion
export const useCheckValue = (isDisabled: Ref<boolean>): { checkeValue: Ref<CheckValue>; handleChange: (e: Event) => void }
=> {
```

或者把 `{ checkeValue: Ref<CheckValue>; handleChange: (e: Event) => void }` 定义成一个类型

2021-01-24 10:52 UTC, danranVm commented on packages/components/checkbox/style/index.less
> +  padding: 0;
这两个 reset.less 里不是已经全局覆盖了嘛？

2021-01-24 10:52 UTC, danranVm commented on packages/components/checkbox/style/index.less
> +  font-size: 14px;
定义变量

2021-01-24 10:52 UTC, danranVm commented on packages/components/checkbox/style/index.less
> +    font-size: 16px;
定义变量 下面还有很多需要定义成变量的，参考 button 组件的做法，

2021-01-24 10:52 UTC, danranVm commented on scripts/gulp/icons/index.ts
> +  ensureDirSync(siteIconAssetsDir)
这个先别提交吧，site 这里我要大改。

2021-01-25 02:11 UTC, liuzaijiang commented on packages/components/checkbox/src/uses.ts
> +}
整个setup抽出来？ 我觉得setup就是一个总入口，需要把其他额外逻辑抽象出来，这样整个vue文件看起来比较简单清晰。

2021-01-25 02:48 UTC, liuzaijiang commented on jest.config.js
> +}
应该是windows下回车的问题

2021-01-25 02:49 UTC, liuzaijiang commented on package.json
> +}
同上

2021-01-25 03:21 UTC, liuzaijiang commented on packages/components/checkbox/src/Checkbox.vue
> +      <span class="ix-checkbox-inner" :tabindex="$attrs.tabindex"></span>
第一个span是包裹层，用来和后面的文本对齐用的，第二个span是我们css模拟出来的勾选框，固定了宽高；

2021-01-25 13:13 UTC, liuzaijiang commented on packages/components/checkbox/src/CheckboxGroup.vue
> +    value: PropTypes.arrayOf(PropTypes.string),
为了检测用户在没有传value的情况下组件还能正常使用

2021-01-25 13:14 UTC, liuzaijiang commented on packages/components/checkbox/docs/index.zh.md
> +| `change` | 点击勾选框时触发 | `Function(checkValue:boolean \| string \| number)` | - |
待定

2021-01-25 13:15 UTC, liuzaijiang commented on packages/components/checkbox/src/uses.ts
> +}
最后将setup抽离成一个单独的函数，重新在一个文件中实现  .vue文件只提供模板和props等设置

2021-01-26 12:38 UTC, danranVm requested changes

2021-01-26 12:38 UTC, danranVm commented on packages/components/checkbox/src/Checkbox.vue
> +    :class="[...classes, $attrs.class]"
```suggestion
    :class="[...classes, $attrs.class]"
    :style="$attrs.style"
```

2021-01-26 14:20 UTC, liuzaijiang commented
修改完毕 @danranVm

2021-01-27 01:28 UTC, danranVm requested changes

2021-01-27 01:28 UTC, danranVm commented on packages/components/checkbox/src/types.ts
> +  >
```suggestion
  classes: ComputedRef<{ 'ix-checkbox-disabled': boolean; 'ix-checkbox-indeterminate': boolean; 'ix-checkbox-checked': boolean }>
```

2021-01-27 01:28 UTC, danranVm commented on packages/components/checkbox/src/types.ts
> +export interface RawBindings {
```suggestion
export interface CheckboxBindings {
```

2021-01-27 01:28 UTC, danranVm commented on packages/components/checkbox/src/setup.ts
> +import { useAttrs } from '@idux/components/core/utils/useAttrs'
```suggestion
import { useAttrs } from '@idux/components/core/utils'
```

在 utils/index.ts 里 export 一下

2021-01-27 02:46 UTC, danranVm approved these changes

2021-01-27 12:20 UTC, danranVm approved these changes
LGTM.

2021-01-28 08:05 UTC, merged