feat(cdk: overlay): add cdk overlay
IduxFE/components pull request #176
Opened 2021-01-30 02:03 UTC by LaamGinghong

fix #113

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IduxFE/components/blob/main/docs/contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-01-30 02:04 UTC, LaamGinghong commented
@coolyuantao @danranVm 先review cdk，后续portal组件会单独review

2021-01-31 15:04 UTC, danranVm reviewed
对这个组件不是很熟悉，只能给一些 API 设计的建议。

2021-01-31 15:04 UTC, danranVm commented on packages/cdk/overlay/src/types.ts
> +  hideDelay: number | false
```suggestion
  hideDelay: number 
```
0 就表示 false ？ showDelay 同理

2021-01-31 15:07 UTC, LaamGinghong commented on packages/cdk/utils/uniqueId.ts
> +const idCollection: Record<string, number> = {}
总不能不同的前缀id也是按顺序下去吧，不过也不是不行

2021-01-31 15:08 UTC, LaamGinghong commented on packages/cdk/overlay/__tests__/overlay.spec.ts
> +const DEFAULT_OVERLAY_OPTIONS: OverlayOptions = {
常量不需要用大写下划线吗

2021-01-31 15:09 UTC, LaamGinghong commented on packages/cdk/overlay/src/types.ts
> +type VueElement = Nullable<ComponentPublicInstance | HTMLElement>
Nullable写在了全局的声明文件定义里面了。

> 另外是否只有 triggerRef 支持 ComponentPublicInstance ? 如果是的话，VueElement => TriggerElement

这个不妥，触发器总不能不允许调用方用原生的元素吧，比如以后的tooltips

2021-01-31 15:11 UTC, LaamGinghong commented on packages/cdk/overlay/src/types.ts
> +  overlayEvents: OverlayPopperEvents
最开始设计时是想在cdk里面触发事件然后将事件抛出去，现在看来是耦合了视图层。
现在的设计是将视图层和逻辑层剥离了。

2021-01-31 15:12 UTC, LaamGinghong commented on packages/cdk/overlay/src/types.ts
> +  overlayEvents: OverlayPopperEvents
并且，分开两个事件的原因是因为，trigger和overlay本身需要绑定到视图的事件是不一样的，所以分开暴露更加容易理解，降低心智负担吧。

2021-01-31 15:13 UTC, LaamGinghong commented on packages/cdk/overlay/src/types.ts
> +  hideDelay: number | false
因为我在参考饿了么的组件设计时，他就是将0理解成我现在的false。但是我觉得不应该去掉0这个含义，因为这本身就是js的一种定义，0不应该被理解成没有延时，所以我增加了布尔值用来判断是否需要使用延时，这种做法在ant里面比较常见吧

2021-02-01 01:22 UTC, danranVm commented on packages/cdk/utils/uniqueId.ts
> +const idCollection: Record<string, number> = {}
嗯，只要保证唯一就好，不一定要顺序。

2021-02-01 01:23 UTC, danranVm commented on packages/cdk/overlay/__tests__/overlay.spec.ts
> +const DEFAULT_OVERLAY_OPTIONS: OverlayOptions = {
只有跨模块（目录）使用的才需要大写下划线

2021-02-01 01:26 UTC, danranVm commented on packages/cdk/overlay/src/types.ts
> +type VueElement = Nullable<ComponentPublicInstance | HTMLElement>
你理解错我意思了，我的意思是：是不是只有 triggerRef  支持 `ComponentPublicInstance  | HTMLElement | null`
如果是的话，就改一下类型的名字，把 `VueElement`  改成 `TriggerElement`, 

> `Nullable写在了全局的声明文件定义里面了。`
你全局的声明文件是不是忘了提交？

2021-02-01 01:27 UTC, danranVm commented on packages/cdk/overlay/src/types.ts
> +  hideDelay: number | false
我建议还是去掉 `false`， 你在用的时候，判断一下 `hideDelay > 0` 不就好了。

2021-02-01 01:30 UTC, LaamGinghong commented on packages/cdk/overlay/src/types.ts
> +type VueElement = Nullable<ComponentPublicInstance | HTMLElement>
> 是不是只有 triggerRef 支持 ComponentPublicInstance | HTMLElement | null
> 如果是的话，就改一下类型的名字，把 VueElement 改成 TriggerElement,

这个可以

2021-02-01 16:16 UTC, LaamGinghong commented
全局滚动不知道该怎么写测试用例

2021-02-02 02:23 UTC, danranVm commented
> 全局滚动不知道该怎么写测试用例

加个 TODO， 暂时不写吧。

2021-02-02 14:18 UTC, LaamGinghong commented
@danranVm 再review吧

2021-02-03 02:18 UTC, danranVm commented on packages/cdk/overlay/src/useOverlay.ts
> +  }
```suggestion
  const overlayVisibility = (visible: boolean): HTMLElement | null => {
    const overlayElement = overlayRef.value
    if (overlayElement) {
        overlayElement.style.display = visible ? 'block' : 'none'
    }
    return overlayElement
  }
```

2021-02-03 02:18 UTC, danranVm commented on packages/cdk/overlay/src/useOverlay.ts
> +    if (!unref(visibility)) {
为什么不用 visibility.value ? 而要用 unref 呢。

2021-02-04 13:36 UTC, danranVm requested changes

2021-02-04 13:36 UTC, danranVm commented on packages/cdk/overlay/src/useOverlay.ts
> +const isHTMLElement = (val: unknown) => toRawType(val).startsWith('HTML')
```suggestion
const isHTMLElement = (val: unknown): val is HTMLElement => toRawType(val).startsWith('HTML')
```

这个丢到 utils/typeof 里去吧。

2021-02-04 13:36 UTC, danranVm commented on packages/cdk/overlay/src/useOverlay.ts
> +    const unrefTrigger = triggerRef.value
```suggestion
    const triggerElement = triggerRef.value
```
另外这里不需要判断 triggerElement  为不为空？

2021-02-04 15:07 UTC, LaamGinghong commented
改好了，再看看？

2021-02-05 02:08 UTC, danranVm approved these changes
LGTM.

2021-02-05 02:09 UTC, merged