feat(comp: core): add component portal
IduxFE/components pull request #178
Opened 2021-01-31 15:54 UTC by LaamGinghong

fix #113

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IduxFE/components/blob/main/docs/contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-02-01 02:09 UTC, danranVm commented on packages/components/core/portal/src/useContainer.ts
> +export default initializeContainer()
```suggestion
export const useContainer = initializeContainer()
```

2021-02-01 09:20 UTC, LaamGinghong commented on packages/components/core/portal/src/useContainer.ts
> +export default initializeContainer()
就是用default导出啊，整个文件就一个导出，非常合理

2021-02-02 14:20 UTC, LaamGinghong commented
是不是确定把这个组件挪到cdk？

2021-02-03 02:23 UTC, danranVm requested changes
丢到 cdk 里面吧。

2021-02-03 02:23 UTC, danranVm commented on packages/components/core/portal/src/types.ts
> +  target: string | HTMLElement
```suggestion
  target: string | () => HTMLElement
```

2021-02-03 09:37 UTC, LaamGinghong commented on packages/components/core/portal/src/types.ts
> +  target: string | HTMLElement
你搞我吧，传个函数进来干嘛

2021-02-04 12:02 UTC, LaamGinghong commented
重新review

2021-02-04 13:18 UTC, danranVm requested changes
移到 cdk 的话，要补个简单的文档和 demo ，不然 start 会报错。

2021-02-04 13:18 UTC, danranVm commented on packages/cdk/portal/index.ts
> +export { default } from './src/Portal.vue'
```suggestion
export IxPortal from './src/Portal.vue'
```

2021-02-04 15:49 UTC, LaamGinghong commented
顺便改了一下之前的文档

2021-02-05 01:25 UTC, danranVm approved these changes
LGTM.

2021-02-05 02:08 UTC, danranVm approved these changes
LGTM.

2021-02-05 02:08 UTC, merged