feat(comp: backtop): add backtop component (#79)
IduxFE/components pull request #185
Opened 2021-02-02 13:11 UTC by imguolao

fix #79

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IduxFE/components/blob/main/docs/contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-02-02 13:13 UTC, imguolao commented
@danranVm @huangtenghui need review.

2021-02-03 03:26 UTC, danranVm requested changes

2021-02-03 03:26 UTC, danranVm commented on packages/components/back-top/src/BackTop.vue
> +    const handleClick = (event: Event) => {
```suggestion
    const handleClick = (evt: MouseEvent) => {
```

event 默认是个全局变量。。。有时候会踩坑。

2021-02-03 03:26 UTC, danranVm commented on packages/components/back-top/src/BackTop.vue
> +          console.warn(`target does not exist: ${props.target}.`)
```suggestion
          Logger.warn(`target does not exist: ${props.target}.`)
```

2021-02-03 03:26 UTC, danranVm commented on packages/components/back-top/src/BackTop.vue
> +      if (props.target) {
这里应该用 computed 或者 watchEfftec 去动态计算 container ？ 否则 target 将无法修改。
同时补充一下这个场景的测试用例

2021-02-03 03:26 UTC, danranVm commented on packages/components/back-top/style/index.less
> +}
```less
@media screen and (max-width: @screen-md) {
  .@{back-top-prefix} {
    right: @back-top-right-md;
  }
}

@media screen and (max-width: @screen-xs) {
  .@{back-top-prefix} {
    right: @back-top-right-xs;
  }
}
```
screen 参考 `Breakpoints` 在 style/variable 目录下定义一下变量，
其他固定的样式值可以定义成变量的，也都定义成变量吧，参考下其他组件

2021-02-03 03:28 UTC, danranVm commented on packages/components/back-top/demo/custom.vue
> +<template>
这个文件删除一下

2021-02-03 03:28 UTC, danranVm commented on packages/components/back-top/demo/basic.vue
> +<template>
这个文件删除一下

2021-02-03 03:35 UTC, danranVm commented on packages/components/back-top/style/index.less
> +@import '../../style/motion/fade.less';
这个应该不用在这里 import ? 在default.less 里 `@import './motion/index.less';`

2021-02-03 09:59 UTC, danranVm requested changes

2021-02-03 09:59 UTC, danranVm commented on packages/components/style/default.less
> +@back-top-right-xs: (@spacing-gutter / 2);
```suggestion
@back-top-right-xs: (@back-top-right-gutter / 2);
```

2021-02-03 09:59 UTC, danranVm commented on packages/components/back-top/style/index.less
> +}
这个应该不需要？ 默认不就是这个吗。

2021-02-04 06:51 UTC, danranVm requested changes

2021-02-04 06:51 UTC, danranVm commented on packages/components/back-top/src/BackTop.vue
> +    <div v-if="visible" class="ix-back-top" @click.stop="handleClick">
这个改成 v-show 是不是会更好些

2021-02-04 07:26 UTC, danranVm approved these changes
LGTM.

2021-02-05 02:17 UTC, merged