feat(comp: divider): add divider component
IduxFE/components pull request #62
Opened 2020-12-23 03:39 UTC by LaamGinghong

link #32 

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IduxFE/components/blob/main/docs/contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2020-12-23 03:48 UTC, LaamGinghong commented
@danranVm 麻烦安排review

2020-12-23 07:28 UTC, danranVm requested changes
样式部分没有太仔细看，后续可能需要重构一波。

2020-12-23 07:28 UTC, danranVm commented on packages/components/divider/__tests__/divider.spec.ts
> +    expect(wrapper.classes()).toContain('ix-divider-with-text-right')
这里还要补充一下 `position` 为 `string` 的测试

2020-12-23 07:28 UTC, danranVm commented on packages/components/divider/docs/index.zh.md
> +| `position` | 文字显示位置 | `left`|`center`|`right`\|string |`center`| 除了三种默认位置以外，还可以传入一个字符串设置文字距离分割线最左端位置。 |
备注这一栏是否有必要？感觉可以跟说明合并在一块

2020-12-23 07:28 UTC, danranVm commented on packages/components/divider/src/Divider.vue
> +    const className = useClassName(props, dividerConfig, !!slots.default)
这里可能会有 bug, 我的 slots 是用 v-if 动态传入的时候，可能导致没有重新计算 class， 例如：
```html
<ix-divider> <template v-if="show">Text</template></ix-divider>
```

2020-12-23 07:28 UTC, danranVm commented on packages/components/divider/src/Divider.vue
> +    const position = props.position ?? config.position
👍

2020-12-23 07:28 UTC, danranVm commented on packages/components/divider/src/Divider.vue
> +        'ix-divider-plain': !!props.plain,
`dashed` 和 `plain` 支持全局配置

2020-12-23 07:39 UTC, danranVm commented on packages/components/divider/src/Divider.vue
> +    },
`position` 和 `type` 都不是必传的, 因为我们有提供全局配置的默认值，这里只要给一个 `default: undefined` 即可
```suggestion
    position: {
      type: String as PropType<DividerPosition>,
     default: undefined,
    },
    type: {
      type: String as PropType<DividerType>,
      default: undefined,
    },
```

2020-12-23 08:10 UTC, danranVm commented
经过我们其他的几个 reviewer 的讨论，建议去掉 `position` 的 `string` 类型，只支持 `left` `center` `right`

十分抱歉，:cry:

2020-12-23 08:28 UTC, LaamGinghong commented on packages/components/divider/docs/index.zh.md
> +| `position` | 文字显示位置 | `left`|`center`|`right`\|string |`center`| 除了三种默认位置以外，还可以传入一个字符串设置文字距离分割线最左端位置。 |
> 备注这一栏是否有必要？感觉可以跟说明合并在一块

感觉说明只是简单的说明情况，介绍API的意义，备注的话是补充说明吧，这是我个人看法

2020-12-23 08:29 UTC, LaamGinghong commented on packages/components/divider/src/Divider.vue
> +        'ix-divider-plain': !!props.plain,
这里是我漏掉了，我会补充上

2020-12-23 08:30 UTC, LaamGinghong commented on packages/components/divider/src/Divider.vue
> +    },
这里是我不太了解Vue3对ts要怎么做兼容，我本来的想法就是所有都是非必填的

2020-12-23 10:57 UTC, LaamGinghong commented on packages/components/core/types/index.ts
> +export type DividerPosition = 'left' | 'center' | 'right' | string
这个已经废弃这个用法了
https://github.com/IduxFE/components/pull/62#issuecomment-749999507

2020-12-23 10:58 UTC, LaamGinghong commented on packages/components/divider/src/Divider.vue
> +    const className = useClassName(props, dividerConfig, !!slots.default)
目前vue3在slot中使用v-if会报警告并且页面也不会重新渲染，暂时忽略这个问题

2020-12-23 13:35 UTC, LaamGinghong commented on packages/components/divider/src/Divider.vue
> +    const className = useClassName(props, dividerConfig, !!slots.default)
经查证，slot内部不能在运行时把内部节点去掉（比如v-if=true)，否则会引发vue的调度器报出警告

2020-12-23 14:10 UTC, danranVm approved these changes

2020-12-27 08:13 UTC, LaamGinghong commented
@danranVm @Pupils-web 麻烦重新review

2020-12-27 08:19 UTC, danranVm approved these changes

2020-12-27 08:20 UTC, danranVm commented
@LaamGinghong  感谢你的 PR, LGTM

2020-12-27 08:21 UTC, merged