Fix#30 comp:image
IduxFE/components pull request #66
Opened 2020-12-24 02:13 UTC by lwh2015

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IduxFE/components/blob/main/docs/contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2020-12-25 04:06 UTC, danranVm requested changes
有一个较大设计的问题需要讨论一下：
- 这个组件可否不在外面套一层 div， 根元素可否直接为 img 标签。这样的好处是，fit, width,hight,alt, 这种API 都不需要提供，我们本身就支持 img 标签的所有属性和方法。

2020-12-25 07:50 UTC, lwh2015 commented
@danranVm please preview the pr once again

2020-12-25 07:57 UTC, zymoplastic commented on packages/components/image/src/Image.vue
> +      :alt="alt"
`img` 除了这几个属性外还有一些有用的原生属性, 能否想点办法支持它们能透传进去?
比如 `v-bind="attrs"` 之类的, 只是注意不要让外部传的 width 直接生效了

2020-12-25 07:57 UTC, zymoplastic commented on packages/components/image/src/Image.vue
> +    const isError = ref(false)
`onError` 里面直接给 `isError` 赋值不太灵活, 我建议维护一个 `status`, `isError` 的值可以依赖这个 `status`.
这个 `status` 是一个小的状态机, 标识当前图片的状态: `normal`, `error`, `loading`, 并且根据 `img` 状态的变化而变化. 组件后面如果要扩展, 比如加一些事件或者占位内容之类方便一些

2020-12-25 08:06 UTC, lwh2015 commented on packages/components/image/src/Image.vue
> +    const imgHeight = computedImg(props.height || imageConfig.height)
那这里仅限用户输入` “”`、`null`、`undefined`的时候再使用全局的配置覆盖，这样子处理吧

2020-12-25 08:10 UTC, zymoplastic commented on packages/components/image/src/Image.vue
> +    const imgHeight = computedImg(props.height || imageConfig.height)
> 那这里仅限用户输入` “”`、`null`、`undefined`的时候再使用全局的配置覆盖，这样子处理吧

先这样可以的

2020-12-25 08:42 UTC, lwh2015 commented on packages/components/image/src/Image.vue
> +      :alt="alt"
原生的属性都会通过`$attrs`传入到组件内，如果在使用中同时在`<ix-image fit="fill" :width="100" :height="100" style="width:200px;height:200px" src="https://cdn.jsdelivr.net/gh/danranvm/image-hosting/images/idux.jpg" />`使用`width`或`height`，会以`style`里的为准，并且相关的原生事件不会冲突，两个都会被触发

2020-12-25 10:35 UTC, lwh2015 commented on packages/components/image/src/Image.vue
> +    const isError = ref(false)
现在图片加载会监听`error`，`load`事件，会在其中改变`imgStatus`的值，后续想要扩展的时候只需要监听这个变量即可

2020-12-25 10:36 UTC, lwh2015 commented
@zymoplastic 代码已经提交，可以再preview一下

2020-12-26 04:51 UTC, danranVm requested changes

2020-12-26 04:51 UTC, danranVm commented on packages/components/image/docs/index.zh.md
> +
API 声明现在这里而不是写在 Demo 中

2020-12-26 04:51 UTC, danranVm commented on packages/components/image/src/Image.vue
> +  <img
这里为什么要用 if else 两个 img 标签？

2020-12-26 04:51 UTC, danranVm commented on packages/components/image/src/Image.vue
> +    width: [String, Number],
既然根元素已经是 img 了，为什么还要提供 width, height,alt,fit ?

2020-12-26 04:51 UTC, danranVm commented on packages/components/image/src/Image.vue
> +    function onLoad() {
```suggestion
    function onLoaded() {
```

2020-12-26 04:51 UTC, danranVm commented on packages/components/image/src/Image.vue
> +    const isShow = ref(false)
```suggestion
    const isShowPreview = ref(false)
```

2020-12-26 04:51 UTC, danranVm commented on packages/components/image/src/Image.vue
> +    const imgSrc = ref(props.src)
对 vue3 的响应式API需要加强理解， proprs 本身就是响应式的

2020-12-26 04:51 UTC, danranVm commented on packages/components/image/src/Image.vue
> +    const imgWidth = computedImg(props.width, imageConfig.width)
对 vue3 的响应式API需要加强理解，这样会失去响应式特性

2020-12-26 04:51 UTC, danranVm commented on packages/components/image/src/ImgPreview.vue
> +        <li class="tools-item zoom-out" :class="scale < 0.2 ? 'tools-item__disabled' : ''" @click="zoomOut">
class 命名不需要使用 BEM，参考 antd 的命名规则

2020-12-26 04:51 UTC, danranVm commented on packages/components/image/src/ImgPreview.vue
> +    let scale = ref(1.0)
这几个数字 magic number 都定义成常量

2020-12-26 04:51 UTC, danranVm commented on packages/components/image/src/types.ts
> +export interface ImageComponent extends ImageProps {}
```suggestion
export interface IxImageComponent extends ImageProps {}
```

2020-12-26 04:51 UTC, danranVm commented on packages/components/image/src/types.ts
> +export interface ImagePreviewComponent extends ImagePreviewProps {}
```suggestion
export interface IxImagePreviewComponent extends ImagePreviewProps {}
```

2020-12-26 04:51 UTC, danranVm commented on packages/components/image/style/index.less
> +@image-prefix-preview: ~'@{image-prefix}-preview';
```suggestion
@image-preview-prefix: ~'@{image-prefix}-preview';
```

2020-12-27 03:14 UTC, danranVm requested changes

2020-12-28 01:55 UTC, lwh2015 commented on packages/components/image/src/Image.vue
> +  <img
这里改为使用div作为占位空间，当图片处于`error`状态时进行替换

2020-12-28 04:12 UTC, lwh2015 commented
@danranVm the pr once again，please.

2020-12-28 09:14 UTC, danranVm requested changes
细节过多。

2020-12-28 09:14 UTC, danranVm commented on packages/components/image/src/Image.vue
> +      context.emit('error')
对外提供一个 `statusChange` 的 emit 即可，
```ts
// 测试一下  `watchEffect` 是不是 immediate 的，如果不是，下面注释的这行代码需要打开，或者sh使用其他方式让 `watchEffect` 变成 immediate 的
// emit('statusChange', imageStatus.value) 
watchEffect(()=>{
  const status = imageStatus.value
  emit('statusChange', status)
})
```

2020-12-28 09:14 UTC, danranVm commented on packages/components/image/src/ImgPreview.vue
> +const SCALE_MIN = 0.2
非暴露给用户的静态常量，使用小驼峰命名即可。

2020-12-28 09:14 UTC, danranVm commented on packages/components/image/src/Image.vue
> +    // init
移除

2020-12-28 09:14 UTC, danranVm commented on packages/components/image/src/types.ts
> +  // please add readonly for every prop
移除

2020-12-29 08:46 UTC, danranVm requested changes
有些代码风格问题，请执行下 `npm run lint-fix`

2020-12-29 08:46 UTC, danranVm commented on packages/components/core/config/types.ts
> +  width?: string | number
这三个都不是可选的吧。

2020-12-29 08:46 UTC, danranVm commented on packages/components/image/src/Image.vue
> +      class="image-error"
```suggestion
      class="ix-image-error"
```

2020-12-29 08:46 UTC, danranVm commented on packages/components/image/src/Image.vue
> +      default: '',
支持默认值的 props 的默认值只能为 undefined

2020-12-29 08:46 UTC, danranVm commented on packages/components/image/src/Image.vue
> +    return imageRect || '100%'
```suggestion
  const size = props[type] ?? imageConfig[type]
  return toCssPixel(size)
```

`toCssPixel` 在 cdk 包中

2020-12-29 08:46 UTC, danranVm commented on packages/components/image/src/Image.vue
> +    const imageWidth = computedImg(props, imageConfig, 'width')
```suggestion
    const imageWidth = computedSize(props, imageConfig, 'width')
```

2020-12-29 08:46 UTC, danranVm commented on packages/components/image/src/ImgPreview.vue
> +      <ul class="preview-tools">
class name 统一使用 ix 前缀

2020-12-29 08:46 UTC, danranVm commented on packages/components/image/src/ImgPreview.vue
> +    let transform = ref('')
```suggestion
    const transform = transform = computed(() => `scale3d(${scale.value}, ${scale.value}, 1) rotate(${rotate.value}deg)`)
```

2020-12-29 08:46 UTC, danranVm commented on packages/components/image/src/ImgPreview.vue
> +    let scale = ref(initScale)
```suggestion
    const scale = ref(initScale)
```

2020-12-29 08:46 UTC, danranVm commented on packages/components/image/src/ImgPreview.vue
> +    let rotate = ref(initRotate)
```suggestion
    const rotate = ref(initRotate)
```

2020-12-29 08:46 UTC, danranVm commented on packages/components/image/src/ImgPreview.vue
> +    }
合并成一个函数吧。

2020-12-29 08:46 UTC, danranVm commented on packages/components/image/src/ImgPreview.vue
> +    }
合并成一个函数吧。

2020-12-29 08:46 UTC, danranVm commented on packages/components/image/style/index.less
> +@tools-h: 46px;
变量命名必须添加组件前缀，参考 button

2020-12-29 10:40 UTC, zymoplastic commented on packages/components/image/src/Image.vue
> +      imageStatus.value = 'error'
我看到这类常量用了很多次, 可以考虑提出来一下

2020-12-29 10:54 UTC, danranVm commented on packages/components/image/src/Image.vue
> +      imageStatus.value = 'error'
对，需要定义一个 ImageStatus 的类型，同时还要声明一下下 emit 。

2020-12-29 12:03 UTC, danranVm approved these changes

2020-12-29 12:03 UTC, zymoplastic approved these changes

2020-12-29 12:04 UTC, danranVm commented
@lwh2015 感谢你的 PR， LGTM.

2020-12-29 12:05 UTC, merged

2020-12-29 12:07 UTC, zymoplastic commented
nice work!