empty
IduxFE/components pull request #96
Opened 2020-12-31 06:47 UTC by qikong333

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows [our guidelines](https://github.com/IduxFE/components/blob/main/docs/contributing.zh.md#commit)
- [ ] Tests for the changes have been added/updated or not needed
- [ ] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2020-12-31 09:31 UTC, Usualminds approved these changes
@qikong333 很棒，提了几个小建议，有空看下

2020-12-31 09:31 UTC, Usualminds commented on packages/components/empty/docs/index.zh.md
> +| :---------: | :------------------------------------------: | :-----------: | :--------: |
| :---------: | :------------------------------------------: | :-----------: | :--------: | 
=>
| :--------- | :------------------------------------------ | :----------- | :--------|

建议 `readme` 表格排布统一 **左对齐**，可读性好一点

2020-12-31 09:31 UTC, Usualminds commented on packages/components/empty/src/Empty.vue
> +    description: PropTypes.string.def('没有数据'),
没有数据 => 暂无数据

参考下 antd，这样描述似乎更准确一点

2020-12-31 09:31 UTC, Usualminds commented on packages/components/empty/src/types.ts
> +  readonly description?: string
建议 `string`  => `string | boolean` ,让  `description`  显示与否可配置，注意下 `template` 中同步修改

2020-12-31 09:31 UTC, Usualminds commented on packages/components/empty/src/Empty.vue
> +      <p class="ix-empty-p">{{ description }}</p>
建议这块 `description ` 支持可配置，看下是否有必要，如果可行
与 `packages/components/empty/src/types.ts` 文件中类型修改同步下，如果  `description `  是 `boolean` 类型 `false`，直接隐藏该标签

2021-01-01 05:38 UTC, danranVm requested changes
另外还需要完善一下单元测试和文档。

2021-01-01 05:38 UTC, danranVm commented on packages/components/empty/src/Empty.vue
> +    description: PropTypes.string.def('没有数据'),
考虑到 i18n, 这里的 props 不应该给默认值。应该再 setup 中使用 computed 计算出来。

2021-01-01 05:38 UTC, danranVm commented on packages/components/empty/src/types.ts
> +  readonly description?: string
@Usualminds 我认为不用支持 boolean, 不然用户传个 true 的时候，还要做特殊处理才行。
假如用户不想显示的话，传个空字符串即可。

2021-01-01 05:38 UTC, danranVm commented on packages/components/empty/docs/index.zh.md
> +| imageStyle  |                   图片样式                   | CSSProperties |     —      |
imageStyle 这个 API 换成 wrapperClassName 会不会更好些？

2021-01-01 05:38 UTC, danranVm commented on packages/components/empty/src/Empty.vue
> +    imageStyle: { type: Object as PropType<CSSProperties>, default: undefined },
```suggestion
    imageStyle: PropTypes.object,
```
如果要保留这个 API 的话，试试用 `PropTypes.object`

2021-01-01 05:38 UTC, danranVm commented on packages/components/empty/src/Empty.vue
> +      <p class="ix-empty-p">{{ description }}</p>
```suggestion
      <p class="ix-empty-description">{{ description }}</p>
```

2021-01-01 05:38 UTC, danranVm commented on packages/components/empty/src/Empty.vue
> +      <p class="ix-empty-p">{{ description }}</p>
另外我认为下面的 DOM 结构可能更合理，参考自 antd
```html
<div class="ix-empty">
  <div class="ix-empty-image">
    <img v-if="image" :src="image" />
    <ix-icon v-else name="empty"  />
  </div>
  <p class="ix-empty-description">
    <slot  name="description">{{ description }}</slot>
  </p>
  <div class="ant-empty-footer">
    <slot />
  </div>
</div>
```

2021-01-01 05:38 UTC, danranVm commented on packages/components/empty/src/Empty.vue
> +    return { props, slots }
```suggestion
```
props 的内容可以直接在 template 中访问到，不需要在 setup 中返回。
slots 同理在 template 中可以用 $slots 获取到，同样不需要在 setup 中返回。

2021-01-01 05:38 UTC, danranVm commented on packages/components/empty/style/index.less
> +  }
```suggestion
.@{empty-prefix} {
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
```
不需要套一个 wrapper

2021-01-01 05:38 UTC, danranVm commented on packages/components/empty/style/index.less
> +  &-p {
```suggestion
  &-description {
```

2021-01-01 10:41 UTC, Usualminds commented on packages/components/empty/src/types.ts
> +  readonly description?: string
@danranVm  这里先确认下 `description` 是否需要 **默认值**，看 `antd` 配置可以支持 `boolean` 类型
- 需要的话还是建议支持 `boolean` 类型
- 不需要的话可不处理

2021-01-02 06:13 UTC, danranVm commented on packages/components/empty/src/types.ts
> +  readonly description?: string
@Usualminds 这里支持 boolean 类型的问题是，用户传 ture 的时候，不好处理。
我们期望的是用户传 false ,或者一个 string, 对吧。
这样的话，不如直接不支持 boolean, 假如用户不想显示，就传一个空字符串，全局配置同理，配置成空字符串即可。

2021-01-04 01:33 UTC, Usualminds commented on packages/components/empty/src/types.ts
> +  readonly description?: string
OK，这个组件内部处理也可以

2021-01-04 02:55 UTC, qikong333 commented
那请问下我还需要根据意见修改吗😂，我还再改 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Joe&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月4日(星期一) 上午9:33
收件人:&nbsp;&quot;IduxFE/components&quot;<components@noreply.github.com&gt;;
抄送:&nbsp;&quot;qikong333&quot;<1513372833@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [IduxFE/components] feat(comp:empty): add component empty (#96)

2021-01-04 02:58 UTC, qikong333 commented on packages/components/empty/src/types.ts
> +  readonly description?: string
那请问下我还需要根据意见修改吗😂，我还再改

2021-01-04 03:05 UTC, Usualminds commented on packages/components/empty/src/types.ts
> +  readonly description?: string
@qikong333  `string` 类型不修改，空字符串的逻辑需要在组件内处理一下，这里不用更改

2021-01-04 03:06 UTC, Usualminds commented on packages/components/empty/src/Empty.vue
> +      <p class="ix-empty-p">{{ description }}</p>
@qikong333 这里需要处理下为 `description` 空的逻辑

2021-01-04 03:07 UTC, qikong333 commented on packages/components/empty/src/types.ts
> +  readonly description?: string
``` 
  const useDescription = (props: EmptyProps) => {
  return computed(() => {
    return props.description !== undefined ? props.description : '暂无数据'
  })
}
```

这样处理可以控制文字是否显示的问题

2021-01-04 03:11 UTC, qikong333 commented on packages/components/empty/docs/index.zh.md
> +| imageStyle  |                   图片样式                   | CSSProperties |     —      |
`这个只是设置图片的样式，应该imageStyle更好一些吧，html代码我已经改成了以下

``` 
  <div class="ix-empty">
    <span class="ix-empty-main">
      <img v-if="image" :src="image" class="ix-empty-img" :style="imageStyle" />
      <ix-icon v-else name="empty" class="ix-empty-icon" />
      <p v-if="!$slots.default" class="ix-empty-descriptionValue">{{ descriptionValue }}</p>
      <div v-if="$slots.default">
        <slot />
      </div>
    </span>
  </div>
```

2021-01-06 01:53 UTC, LaamGinghong commented
测试覆盖率没有达标，本地看看哪个地方漏了

2021-01-06 01:54 UTC, LaamGinghong commented
到时候合成一个commit，commit message 用英文呗。
提的pr里面带上 fix issue号

2021-01-06 14:35 UTC, danranVm reviewed
是重新 fork 了吗？ 那么这个 PR 可能需要关掉，重新创建一个新的 PR 。

2021-01-06 14:50 UTC, qikong333 commented
是的，已经重新建过了------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;danranVm&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月6日(星期三) 晚上10:36
收件人:&nbsp;&quot;IduxFE/components&quot;<components@noreply.github.com&gt;;
抄送:&nbsp;&quot;qikong333&quot;<1513372833@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [IduxFE/components] feat(comp:empty): add component empty (#96)

2021-01-06 15:17 UTC, closed without merging