feat(comp: space): add component space
IduxFE/components pull request #97
Opened 2020-12-31 08:07 UTC by LaamGinghong

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IduxFE/components/blob/main/docs/contributing.zh.md#commit)
- [x] Tests for the changes have been added/updated or not needed
- [x] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

## Other information

2020-12-31 08:17 UTC, LaamGinghong commented
@danranVm 麻烦安排一下review

2021-01-03 03:07 UTC, danranVm requested changes

2021-01-03 03:07 UTC, danranVm commented on packages/components/space/src/Space.vue
> +        } else current.className = `ix-space-item-${size}`
```suggestion
        } else {
        current.className = `ix-space-item-${size}`
        }
```
另外在做 style 和 className 赋值的时候，需不需要考虑用户本身节点上的 style 和 className？ 你这样做会不会直接把用户自己设置的给干掉了。

2021-01-03 03:07 UTC, danranVm commented on packages/components/space/style/index.less
> +      margin-bottom: @margin-md;
参考 button 组件, 需要在 default.less 中定义 `@space-item-margin-bottom: @margin-md;`

```suggestion
      margin-bottom: @space-item-margin-bottom;
```

2021-01-03 03:07 UTC, danranVm commented on packages/components/space/style/mixins.less
> +  small: @margin-sm;
参考 button 组件, 需要在 default.less 中定义相关变量

2021-01-03 03:07 UTC, danranVm commented on packages/components/space/style/mixins.less
> +        margin: if(@key=horizontal, 0 @margin-sm, @margin-sm 0);
参考 button 组件, 需要在 default.less 中定义相关变量

2021-01-04 03:18 UTC, LaamGinghong commented on packages/components/core/utils/getSlotNodeList.ts
> +  const currentSlot = slots[key]!(options)
ide提示需要进行判断😓

> 我怎么感觉这里不需要非空断言呢。

2021-01-04 03:19 UTC, LaamGinghong commented on packages/components/space/__tests__/space.spec.ts
> +  },
测试用例也改成setup？用setup能setData吗

> 这段改成 setup ？

2021-01-04 03:21 UTC, LaamGinghong commented on packages/components/space/demo/CustomSize.vue
> +    <ix-button>Button</ix-button>
> 所有的示例里都加一个纯文本吧。

加了一些，感觉有些不加更好，我的示例基本都是照着ant来写的

2021-01-04 03:23 UTC, LaamGinghong commented on packages/components/space/docs/index.zh.md
> +| `split` | 设置拆分 | string | - | - | 设置间隔分割符，当传入 split 时，内部间距会被分隔符替代；除了这种方式，你还可以设置 `v-slot: split` 的方式设置分隔符，优先级高于 prop |
文档我将 props 和 slots 拆开了，忘了当时我们是怎么说的了😓

2021-01-04 03:24 UTC, LaamGinghong commented on packages/components/space/src/Space.vue
> +      if (children.length - 1 !== size.length) {
> 这个 -1 是因为需要把 split slot 减掉？ split slot 是一定存在的么？

因为间隔肯定是比元素少一个的啊

2021-01-04 03:25 UTC, LaamGinghong commented on packages/components/space/src/Space.vue
> +        } else current.className = `ix-space-item-${size}`
> 另外在做 style 和 className 赋值的时候，需不需要考虑用户本身节点上的 style 和 className？ 你这样做会不会直接把用户自己设置的给干掉了。

不会，因为这个赋值的本身是组件内部的元素节点，不会影响到调用方传进来的模板

2021-01-04 03:41 UTC, LaamGinghong commented on packages/components/space/__tests__/space.spec.ts
> +  },
> 这段改成 setup ？

这是测试用例啊，这个也改成setup？改了之后工具支不支持 setData ？

2021-01-04 03:44 UTC, LaamGinghong commented on packages/components/space/src/Space.vue
> +        <span v-if="split" :key="child.id + 'span'" class="ix-space-split">
> 这个 Key 好像没什么意义？

上面用了 `v-for`：

```html
<template>
  <div class="ix-space" :class="className">
    <template v-for="(child, index) in spaceList" :key="child.id">
      <div class="ix-space-item" :class="child.className" :style="child.style">
        <component :is="child.node" />
      </div>
      <slot v-if="index < spaceList.length - 1" name="split">
        <span v-if="split" :key="child.id + 'span'" class="ix-space-split">
          {{ split }}
        </span>
      </slot>
    </template>
  </div>
</template>
```

2021-01-04 03:45 UTC, LaamGinghong commented on packages/components/space/docs/index.zh.md
> +| `split`   | 分隔符           |
感觉出一个书面的文档示例，文档到底该怎么写，会比较好

2021-01-04 03:48 UTC, LaamGinghong commented
@danranVm 修改了一部分提出的问题，另一部分我提出了解答，麻烦请重新review

2021-01-05 01:36 UTC, danranVm requested changes

2021-01-05 01:36 UTC, danranVm commented on packages/cdk/utils/getSlotNodeList.ts
> +export function getSlotNodeList(slots: Slots, key = 'default', options: unknown[] = []): VNode[] {
这个函数名字修改为 `getSlotNodes` 会不会更好些? 
同时把这个函数移到 vNode.ts 的目录吧，还有单元测试也一样

2021-01-05 01:36 UTC, danranVm commented on packages/components/space/docs/index.zh.md
> +| `direction` | 间距方向 | `vertical \| horizontal` | `horizontal` | - | - |
这两个要不要考虑支持下 全局配置?

2021-01-05 01:36 UTC, danranVm commented on packages/components/space/src/Space.vue
> +        <span v-if="split" :key="child.id + 'span'" class="ix-space-split">
你的 `template` 上已经绑定了一个 key, 这的 key 就没什么意义了吧。

2021-01-05 01:36 UTC, danranVm commented on packages/components/space/src/Space.vue
> +    const spaceList = useSpaceList(props, spaceConfig, children, !!slots.split)
slots.split 是不是也要改成 computed ?

2021-01-05 01:43 UTC, LaamGinghong commented on packages/components/space/docs/index.zh.md
> +| `direction` | 间距方向 | `vertical \| horizontal` | `horizontal` | - | - |
我想了下，这两个属性很难通用，基本都会单独配置，设置成全局好像不是很好

2021-01-05 02:21 UTC, danranVm approved these changes

2021-01-05 02:21 UTC, danranVm commented
感谢你的 PR， LGTM.

2021-01-05 02:21 UTC, merged